# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbcb4c2b61ce89a6e9ab995b4c2c9dace8c41e4cbd64f9b111c7859fdf52ce45109ccd126e8283d9fe8693c343a496e536acbdb00328c1a666c731fde73c393e

test:
  secret_key_base: e6cf7bbbb51f33a0936706bd485d5caf3d2802391ef13449778abb8aa599b42ff1d6108d21f55684c7a38bbc36f8b8c8f4ce369876eeacca6ebe034407b521d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
